# Generated by Django 4.0 on 2022-05-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserr', '0003_alter_dannie_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dannie',
            name='url',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
